In [1]:
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.cluster import KMeans

In [8]:
yf.Tickers()

TypeError: Tickers.__init__() missing 1 required positional argument: 'tickers'

In [10]:
# data = yf.download("BTC-USD, ETC-USD", period="10d")
# data = yf.download(["BTC-USD", "ETC-USD"], period="10d")
# data = data.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index(level=1)

[*********************100%%**********************]  2 of 2 completed

In [3]:
data = pd.read_csv("currency-dataset.csv")
data.set_index("Date", inplace=True)

In [11]:
from main_service import start
from data_loader import load_data

load_data()

Using the cached dataset..

,ADA-USD,ATOM-USD,AVAX-USD,BCH-USD,BNB-USD,BTC-USD,CRO-USD,DAI-USD,DOGE-USD,DOT-USD,...,SOL-USD,STX4847-USD,TRX-USD,UNI7083-USD,USDC-USD,USDT-USD,VET-USD,XLM-USD,XMR-USD,XRP-USD
Date,,,,,,,,,,,,,,,,,,,,,
2023-03-01,0.360356,12.771041,17.761023,134.239853,302.907471,23646.550781,0.079538,1.000209,0.081964,6.534181,...,22.506432,0.987501,0.069878,6.842951,1.000146,1.000144,0.028120,0.088102,152.668167,0.383879
2023-03-02,0.350206,12.450935,17.447031,131.717331,299.946167,23475.466797,0.076786,0.999563,0.080520,6.326915,...,21.984879,0.925750,0.069651,6.631044,1.000295,1.000091,0.027232,0.087452,151.075195,0.377580
2023-03-03,0.342737,11.998372,16.654383,126.123589,290.282837,22362.679688,0.072902,0.999861,0.076777,6.033932,...,21.399353,0.847762,0.067159,6.267341,1.000000,1.000100,0.025400,0.085618,144.905441,0.377671
2023-03-04,0.336499,11.832651,16.117805,124.414520,289.503876,22353.349609,0.072962,0.999939,0.074556,5.912604,...,20.966839,0.732043,0.066684,6.152785,1.000048,1.000114,0.024432,0.083604,146.698761,0.373813
2023-03-05,0.337102,12.025496,16.159338,124.038612,288.699707,22435.513672,0.073556,0.999900,0.074795,5.980068,...,20.978584,0.749983,0.067256,6.352076,1.000010,1.000107,0.024345,0.082753,149.534653,0.367194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-02-26,0.619736,11.136368,39.336189,274.898132,401.643890,54522.402344,0.098102,0.999888,0.089389,8.104343,...,109.918533,2.908405,0.139920,10.592780,0.999950,1.000718,0.050625,0.117967,129.613281,0.551405
2024-02-27,0.624216,11.212992,39.268646,292.519379,394.995636,57085.371094,0.103539,0.999768,0.097671,8.371495,...,108.388084,2.948646,0.142885,10.856444,0.999921,1.000354,0.048922,0.122972,130.061203,0.586258
2024-02-28,0.631059,11.412553,40.294788,296.793793,415.771606,62504.789062,0.104241,1.000062,0.116582,8.342619,...,118.052200,3.100055,0.142234,10.934174,0.999952,1.001061,0.048700,0.121081,133.892288,0.575811
2024-02-29,0.655646,11.285693,40.935387,298.562378,399.778717,61198.382812,0.109169,0.999775,0.117185,8.255025,...,125.711517,2.898550,0.140578,11.133665,0.999754,1.000402,0.047718,0.121939,137.173569,0.586325
2024-03-01,0.686563,11.402323,42.354828,315.402985,407.799286,62446.125000,0.116376,0.999853,0.123473,8.477266,...,133.700150,2.962958,0.141341,11.405329,0.999916,1.000336,0.048629,0.125284,139.194946,0.592914

In [10]:
clustered_data.groupby("Cluster").count()

         PC0  PC1
Cluster
0         29   29
1          1    1